# Activation Functions

In [1]:
import numpy as np

In [16]:
def sigmoid(X):
    return 1/(1+np.exp(-X))
def relu(X):
    return np.maximum(0,X)
def softmax(X):
    expo = np.exp(X)
    expo_sum = np.sum(np.exp(X))
    return expo/expo_sum
def tanh(x):
    return np.tanh(x)
def lrelu(X, alpha):
    return np.where(X > 0, X, X * alpha)
def heaviside(X, t):
    return np.where((X-t) != 0, np.maximum(0, np.sign(X-t)), 0.5) 

## Examples

In [4]:
inp = np.array([
    [1, 0.5, 0.2],
    [-1, -0.5, -0.2],
    [0.1, -0.1, 0]
])

In [5]:
sigmoid(inp)

array([[0.73105858, 0.62245933, 0.549834  ],
       [0.26894142, 0.37754067, 0.450166  ],
       [0.52497919, 0.47502081, 0.5       ]])

In [7]:
relu(inp)

array([[1. , 0.5, 0.2],
       [0. , 0. , 0. ],
       [0.1, 0. , 0. ]])

In [8]:
softmax(inp)

array([[0.26158566, 0.15865973, 0.11753802],
       [0.03540177, 0.05836765, 0.07878809],
       [0.10635279, 0.0870743 , 0.09623199]])

In [9]:
tanh(inp)

array([[ 0.76159416,  0.46211716,  0.19737532],
       [-0.76159416, -0.46211716, -0.19737532],
       [ 0.09966799, -0.09966799,  0.        ]])

In [15]:
lrelu(inp, 0.1)

array([[ 1.  ,  0.5 ,  0.2 ],
       [-0.1 , -0.05, -0.02],
       [ 0.1 , -0.01,  0.  ]])

In [17]:
heaviside(inp, 0.1)

array([[1. , 1. , 1. ],
       [0. , 0. , 0. ],
       [0.5, 0. , 0. ]])