# Autoencoder

<img src='img/autoencoder.png' style='height:300px; width: auto;'/>

In [1]:
import numpy as np

In [32]:
def heaviside(X, t):
    return np.where((X-t) != 0, np.maximum(0, np.sign(X-t)), 0.5) 
def sigmoid(X):
    return 1/(1+np.exp(-X))
def euc(x, z):
    return np.linalg.norm(x - z)

def autoencoder(X, Wji):
    """ Simple Autoencoder
        Parameters
        ----------
        X: np.array
            Feature vectors
        Wji: np.array
            Weights (same for encoder and decoder)
    """
    # ENCODING
    encoded = []
    for i, x in enumerate(X):
        encoded.append(sigmoid(np.matmul(Wji, x)))
    encoded = np.array(encoded)
    print('encoded:', encoded)
    # DECODING
    decoded = []
    for i, y in enumerate(encoded):
        decoded.append(sigmoid(np.matmul(Wji.T, y)))
    decoded = np.array(decoded)
    print('decoded:', decoded)
    error = euc(X, decoded)
    print('error:', error)

## Examples

In [33]:
Wji = np.array([
    [-0.7057, 1.9061, 2.6605, -1.1359], 
    [0.4900, 1.9324, -0.4269, -5.1570],
    [0.9438, -5.4160, -0.3431, -0.2931],
    [0.5421, -2.4902, 0.4890, 1.2931]
               ])
X = np.array([
    [1, 0, 1, 0], 
    [0, 1, 0, 1],
    [1, 1, 0, 0],
             ])

In [34]:
autoencoder(X, Wji)

encoded: [[0.87596909 0.51576977 0.64581644 0.7371291 ]
 [0.68356416 0.0382504  0.0033047  0.23199151]
 [0.76859593 0.91851954 0.01129317 0.12476068]]
decoded: [[0.65558373 0.06494998 0.90458238 0.052603  ]
 [0.4170812  0.68595015 0.87153543 0.33744563]
 [0.49649198 0.94624806 0.846819   0.00427011]]
error: 1.606044600671333
