# Extreme learning machines

<img src="img/extreme.png"/>

In [1]:
import numpy as np

In [64]:
def heaviside(X, t):
    return np.where((X-t) != 0, np.maximum(0, np.sign(X-t)), 0.5) 
def extreme_learning(X, V, w):
    # augment X
    X = np.insert(X, 0, 1., axis=1)
    print('V · X.T', np.dot(V, X.T))
    heavy_XV = heaviside(np.dot(V, X.T), 0)
    # The response of the output neuron to a single exemplar is defined as z = wy. 
    # The response to all input patterns is given by:
    augmentation = np.array([np.ones(heavy_XV.shape[1])])
    heavy_XV = np.concatenate((augmentation, heavy_XV), axis=0)
    print('heavy_XV', heavy_XV)
    response = np.dot(w, heavy_XV)
    print('response:', response)


## Examples

In [65]:
X = np.array([
    [0, 0],
    [0, 1], 
    [1, 0],
    [1, 1]
])

V = np.array([
    [-0.62, 0.44, -0.91],
    [-0.81, -0.09, 0.02],
    [0.74, -0.91, -0.6],
    [-0.82,-0.92, 0.71],
    [-0.26, 0.68, 0.15],
    [0.80, -0.94, -0.83]
])

w = np.array([0, 0,0,-1,0,0,2])

In [66]:
extreme_learning(X, V, w)

[[-0.62 -1.53 -0.18 -1.09]
 [-0.81 -0.79 -0.9  -0.88]
 [ 0.74  0.14 -0.17 -0.77]
 [-0.82 -0.11 -1.74 -1.03]
 [-0.26 -0.11  0.42  0.57]
 [ 0.8  -0.03 -0.14 -0.97]]
[[1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 1.]
 [1. 0. 0. 0.]]
response: [ 1. -1.  0.  0.]
