# Neural network forward propagation

In [1]:
import numpy as np
from math import exp

In [2]:
def tangent(x):
    return 2 / (1 + np.exp(-2 * x)) -1
def sigmoid(x):
    return 1/(1 + np.exp(-x))
def forward_propagation(x, Wji, Wj0, Wkj, Wk0): 
    """ NN forward propagation step
        x: np.array
            Sample
        Wji: np.array
            First layer weights vector
        Wj0: np.array
            First layer bias
        Wkj: np.array
            Output layer weights vector
        Wk0: np.array
            Output layer bias
    """
    print('x:', x)
    y = tangent(np.matmul(Wji, x) + Wj0)
    print('y:', y)
    z = sigmoid(np.matmul(Wkj, y) + Wk0)
    print('z:', z)
    return z

## Examples

In [3]:
Wji = np.array([[-0.7057, 1.9061, 2.6605, -1.1359], 
                [0.4900, 1.9324, -0.4269, -5.1570],
                [0.9438, -5.4160, -0.3431, -0.2931]
               ])
Wj0 = np.array([4.8432, 0.3973, 2.1761])
Wkj = np.array([[-1.1444, 0.3115, -9.9812],
                [0.0106, 11.5477, 2.6479]
               ])
Wk0 = np.array([2.5230, 2.6463])
X = np.array([[1, 0, 1, 0], 
            [0, 1, 0, 1],
            [1, 1, 0, 0],
             ])

In [4]:
outputs = []
for x in X:
    z = forward_propagation(x, Wji, Wj0, Wkj, Wk0)
    outputs.append(z)
#remove the e-n formatting for decimal numbers
np.set_printoptions(suppress=True)
print('outputs:', outputs)

[1 0 1 0]
y: [0.99999751 0.43041017 0.99228292]
z: [2.26735732e-04 9.99964806e-01]
[0 1 0 1]
y: [ 0.99997338 -0.99302169 -0.99829417]
z: [9.99983848e-01 1.06110932e-05]
[1 1 0 0]
y: [ 0.99998874  0.99291518 -0.9799421 ]
z: [0.99998955 0.99999015]
[array([0.00022674, 0.99996481]), array([0.99998385, 0.00001061]), array([0.99998955, 0.99999015])]
