## Karhunen-Loève Transform for PCA

In [2]:
import numpy as np
from sklearn.decomposition import PCA

In [3]:
data = np.array([
    [1, 2, 1],
    [2, 3, 1],
    [3, 5, 1],
    [2, 2, 1]
])

In [4]:
pca = PCA(n_components=2)
pca.fit(data)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [9]:
# eigenvalues and eigenvectors
pca.components_

array([[ 0.47185793,  0.8816746 ,  0.        ],
       [ 0.8816746 , -0.47185793, -0.        ]])

In [5]:
# transformed data
pca.transform(data)

array([[-1.35353252, -0.40981667],
       [ 0.        ,  0.        ],
       [ 2.23520712, -0.06204125],
       [-0.8816746 ,  0.47185793]])

<p style='color:green'>What is the proportion of the variance explained by the first two principal components in the preceding question?</p>
The proportion of the variance is given by sum of eigenvalues for selected components divided by the sum of all
eigenvalues.

In [42]:
transf = pca.transform(data) - np.mean(pca.transform(data).T, axis=1)
transf.T

array([[-1.35353252e+00, -2.77555756e-17,  2.23520712e+00,
        -8.81674599e-01],
       [-4.09816673e-01,  0.00000000e+00, -6.20412523e-02,
         4.71857926e-01]])

In [43]:
np.cov(transf.T)

array([[ 2.53518376e+00, -3.14563190e-16],
       [-3.14563190e-16,  1.31482908e-01]])