# Binary-coded SVM

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
def SVM(SV, y):
    matrix = []
    for i, sv1 in enumerate(SV):
        temp = []
        for j, sv2 in enumerate(SV):
            temp.append(y[j] * np.dot(sv2.T,  sv1))
        #temp.append(y[i])
        temp.append(1)
        matrix.append(np.array(temp))
    
    y_new = list(y)
    y_new.append(0)
    y_new = np.array(y_new)
    matrix.append(y_new)  
    matrix = np.matrix(np.array(matrix))
    
    matrix_inv = np.linalg.inv(matrix)
    
    print(matrix)
    print(matrix_inv)
    print(y_new)
    
    lambdas = np.dot(np.array(matrix_inv), y_new)
    lambdas = np.array(lambdas)
    
    print(lambdas)
    w = []
    for i in range(len(SV)):
        w.append(y[i] * np.dot(SV[i], lambdas[i]))
    w = np.array(w)
    W = w.sum(axis=0)
    print(W, lambdas[-1])
    return(W, lambdas[-1])

- we need ceil(log2(R)) classifiers; R = # of classes
- the combination of outputs of the classifiers determines the label

## Examples

In [4]:
X = np.array([
    # class_1
    [0, 10],
    [1, 8],
    [2, 9],
    [2, 8],
    [3, 10],
    [3, 9],
    [4, 10],
    [4, 9],
    [4, 8],
    [5, 9],
    # class_2
    [2, 6],
    [0, 5],
    [4, 5],
    [2, 4],
    [5, 3],
    [0, 2],
    [2, 2],
    [5, 2],
    [2, 1],
    [3, 0],
    # class_3
    [9, 6],
    [8, 5],
    [7, 3],
    [8, 3],
    [9, 3],
    [10, 3],
    [7, 1],
    [8, 1],
    [8, 0],
    [9, 0]  
])
y = np.array([
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3
])
# SVs
SV12_X = np.array([
    [1, 8], [2, 8], [4, 8], [2, 6], [9, 6]
])
SV12_y = np.array([1, 1, 1, -1, -1])

SV23_X = np.array([
    [7, 3], [7, 1], [5, 9], [5, 3], [5, 2]
])
SV23_y = np.array([1, 1, -1, -1, -1])

In this case: 
- (+1, -1) -> class_1
- (-1, -1) -> class_2
- (-1, +1) -> class_3

In [6]:
W_12, W0_12 = SVM(SV12_X, SV12_y)
W_23, W0_23 = SVM(SV23_X, SV23_y)

[[  65   66   68  -50  -57    1]
 [  66   68   72  -52  -66    1]
 [  68   72   80  -56  -84    1]
 [  50   52   56  -40  -54    1]
 [  57   66   84  -54 -117    1]
 [   1    1    1   -1   -1    0]]
[[ 2.49116863e+13 -1.87108426e+14  1.62196740e+14  4.27831133e+13
  -4.27831133e+13 -3.81625782e+00]
 [ 7.06733708e+13  6.88456112e+13 -1.39518982e+14 -4.99587621e+13
   4.99587621e+13  1.08225108e-01]
 [-9.55850570e+13  1.18262815e+14 -2.26777579e+13  7.17564876e+12
  -7.17564876e+12  7.08032708e-01]
 [ 3.08688286e+13 -6.05191508e+13  2.96503222e+13  4.06168798e+12
  -4.06168798e+12 -5.03318903e+00]
 [-3.08688286e+13  6.05191508e+13 -2.96503222e+13 -4.06168798e+12
   4.06168798e+12  1.03318903e+00]
 [-4.38672439e-01 -1.13997114e+00 -1.42135642e+00  3.94227994e+00
   5.77200577e-02 -4.21609196e-14]]
[ 1  1  1 -1 -1  0]
[ 0.6953125  -0.0390625  -0.13769531  0.63134766 -0.12744141 -7.        ]
[-0.04931641  1.125     ] -6.999999999999993
[[  58   52  -62  -44  -41    1]
 [  52   50  -44  -38 