# Whitening

In [1]:
import numpy as np

In [2]:
def whitening(X):
    """
    Function to compute ZCA whitening matrix (aka Mahalanobis whitening).
    INPUT:  X: [M x N] matrix.
        Rows: Variables
        Columns: Observations
    OUTPUT: ZCAMatrix: [M x M] matrix
    """
    # Covariance matrix [column-wise variables]: Sigma = (X-mu)' * (X-mu) / N
    sigma = np.cov(X, rowvar=True) # [M x M]
    # Singular Value Decomposition. X = U * np.diag(S) * V
    U,S,V = np.linalg.svd(sigma)
        # U: [M x M] eigenvectors of sigma.
        # S: [M x 1] eigenvalues of sigma.
        # V: [M x M] transpose of U
    # Whitening constant: prevents division by zero
    epsilon = 1e-5
    # ZCA Whitening matrix: U * Lambda * U'
    ZCAMatrix = np.dot(U, np.dot(np.diag(1.0/np.sqrt(S + epsilon)), U.T)) # [M x M]
    return ZCAMatrix

## Examples

In [6]:
X = np.array([[0, 2, 2], [1, 1, 0], [2, 0, 1], [1, 3, 5], [10, 10, 10] ]) # Input: X [5 x 3] matrix
whitening_mat = whitening(X) # get ZCAMatrix
print(whitening_mat) # [5 x 5] matrix
whitened = np.dot(whitening_mat, X) # project X onto the ZCAMatrix
print(whitened) # [5 x 3] matrix

[[204.84907554 -18.49407801 129.87276848 -74.39053444   0.        ]
 [-18.49407801 260.57984302  74.14200101  92.80176798   0.        ]
 [129.87276848  74.14200101 112.21299652 -18.41123354   0.        ]
 [-74.39053444  92.80176798 -18.41123354  56.23369561   0.        ]
 [  0.           0.           0.           0.         316.22776602]]
[[ 166.86092451  168.03246973  167.61824734]
 [ 501.66561302  501.99699093  501.16268489]
 [ 280.15676051  278.65383738  279.90236581]
 [ 112.21299652  112.72178592  113.97617561]
 [3162.27766017 3162.27766017 3162.27766017]]
